export const includesBanksVariant = {
  '3/4': ['Bank 3/4', '3/4'],
  'A-Bank': ['A-Bank', 'А-Банк', 'А-БАНК', 'Aktsent-Bank', 'А Банк', 'А-банк'],
  Akkordbank: ['akord bank', 'Akord Bank', 'Akordbank', 'Акордбанк'],
  'Alfa-Bank': ['Alpha-Bank', 'Alfa Bank', 'Alfa-Bank', 'AlfaBank', 'Alʹfa-Bank'],
  Arcade: ['Bank Arcada', 'Arkada', 'аркад'],
  Alliance: ['At "Bank Alʹyans"', 'Банк Алянс'],
  'ASVIO BANK': ['Asvio Bank', 'Асвіо Банк', 'Асвио Банк'],
  'BTA Bank': ['BTA BANK', 'БТА Банк'],
  'CLEARING HOUSE': ['Clearing House'],
  'Commercial Industrial Bank': [
    'Komertsiynyy Industrialʹnyy Bank',
    'Komertsinyy Industrialʹnyy Bank',
    'ComInBank',
  ],
  'Credit Agricole': ['Credit Agricole', 'Креді Агріколь', 'Kredi Ahrikol'],
  'CREDIT DNEPR': ['Credit Dnepr'],
  'Credit Europe Bank': ['Credit Europe Bank', 'Kredyt Europe Bank'],
  'CREDITWEST BANK': ['Creditwest Bank'],
  East: ['East Bank'],
  EVROPROMBANK: ['evroprombank', 'Европромбанк'],
  Family: ['family bank', 'Фамильный банк'],
  Globe: ['Globe bank'],
  'First Investment Bank': ['pinbank', 'ПЕРШИЙ ІНВЕСТИЦІЙНИЦ БАНК', 'PinBank'],
  Grant: ['grant bank', 'Грант Банк'],
  'Idea Bank (Plus Bank)': ['idea Bank', 'Idea Bank', 'Idea bank', 'IdeaBank'],
  Industrialbank: ['Industrialbank', 'ІНДУСТРІАЛБАНК'],
  'International investment bank': ['International Investment Bank'],
  Lions: ['Lions Bank'],
  KomInvestBank: ['KomInvestBank', 'Kominvestbank'],
  Kredobank: ['Kredobank', 'KredoBank', 'КредоБанк', 'Кредобанк'],
  Megabank: ['Megabank', 'Mehabank', 'MegaBank'],
  'MOTOR-BANK': ['Motor Bank', 'МОТОР-БАНК', 'Мотор-банк', 'Мотор Банк'],
  'Pravex-Bank': [
    'Pravex Bank',
    'Praveks-Bank',
    'Правекс Банк',
    'ПРАВЭКС-БАНК',
    'Pravex-Bank',
    'Pravex-bank',
  ],
  Radabank: ['Radabank', 'РАДАБАНК', 'Радабанк'],
  'OTP Bank': ['Otp Bank', 'Otpbank', 'OTP Банк', 'ОТП Банк', 'OTP Bank', 'Otp'],
  Oschadbank: ['Oschadbank'],
  'OXY BANK': ['Oksi Bank'],
  'Piraeus Bank ICB': ['Piraeus Bank', 'Піреус Банк', 'Pireus Bank'],
  PIVDENNY: ['Pivdennyi', 'ПИВДЕННЫЙ', 'Pivdennyy', 'Pivdenniy'],
  PrivatBank: ['Privatbank', 'Pryvatbank', 'PrivatBank'],
  Prominvestbank: ['Prominvestbank', 'ПРОМИНВЕСТБАНК'],
  'Raiffeisen Bank Aval': ['Rayffayzen', 'Raiffeisen'],
  Sich: ['Sich'],
  TASkombank: ['Taskombank'],
  'Trust Capital': ['Trast-Capital', 'Траст-капітал'],
  'Ukrainian Building and Investment Bank': [
    'Ukrbudinvestbank',
    'УКРАИНСКИЙ СТРОИТЕЛЬНО-ИНВЕСТИЦИОННЫЙ БАНК ПАО',
  ],
  UGB: ['ukrgazbank', 'Ukrhazbank'],
  'Ukrainian Capital': ['Ukrainian capital'],
  Ukreximbank: ['Ukreximbank', 'UkrEximBank', 'Ukreksimbank'],
  UkrSibbank: ['Ukrsibbank', 'UkrSibBank', 'UkrSibbank', 'UKRSIBBANK', 'УКРСИББАНК'],
  'Unex Bank': ['Unex Bank', 'Юнекс Банк', 'UNEX BANK'],
  'Universal Bank': ['Universal Bank', 'monobank'],
}
