export const commands = {
  SHARE_LOCATION: 'share_location',
  CHECK_CITY: 'check_city',
  CONFIRM_CITY: 'Да, указан верный город',
  CHOOSE_CURRENCY: 'Выбрать валюту',
  CHOOSEN_CURRENCY: 'choosen_currency',
  FIND_BANKS: 'Найти выгодные банки',
  CHOOSEN_BUY_OR_SELL: 'choosen_buy_or_sell',
  BUY_OR_SELL: 'Продажа/Покупка',
  SELL: 'Продажа',
  BUY: 'Покупка',
  EXIST_CURRENCY: 'Выбрать другую валюту',
  EXIST_ACTION: 'Выбрать другое действие',
  CHANGE_CURRENCY: 'Выбрать другую валюту',
  CHANGE_ACTION: 'Выбрать другое действие',
  CONVERSATION_STARTED: '/conversation_started',
  GO_BACK: 'Вернуться назад',
}
export const currencies = {
  USD: 'USD',
  EUR: 'EUR',
  RUB: 'RUB',
  CHF: 'CHF',
  GBP: 'GBP',
  AUD: 'AUD',
  CAD: 'CAD',
  CZK: 'CZK',
  DKK: 'DKK',
  JPY: 'JPY',
  NOK: 'NOK',
  PLN: 'PLN',
  SEK: 'SEK',
  HUF: 'HUF',
  BGL: 'BGL',
}

export const markup = {
  initialKeyboard: () => [['Выбрать валюту'], ['Продажа/Покупка'], ['Найти выгодные банки']],
  chooseCurrency: () => [
    ['USD'],
    ['EUR'],
    ['RUB'],
    ['CHF'],
    ['GBP'],
    ['AUD'],
    ['CAD'],
    ['CZK'],
    ['DKK'],
    ['JPY'],
    ['NOK'],
    ['PLN'],
    ['SEK'],
    ['HUF'],
    ['BGL'],
    ['Вернуться назад'],
  ],
  checkCity: () => [
    ['Да, указан верный город'],
    ['Хмм, произошла ошибка, я укажу нужный город'],
    ['Вернуться назад'],
  ],
  chooseBuyOrSell: () => [['Продажа'], ['Покупка'], ['Вернуться назад']],
  alreadyExistCurrency: () => [['Выбрать другую валюту'], ['Вернуться назад']],
  alreadyExistAction: () => [['Выбрать другое действие'], ['Вернуться назад']],
  goBack: () => [['Вернуться назад']],
}
